services:
  next-js:
    expose:
      - "3000"
    ports:
      - "${PORT}:3000"
    build: ./nextjs/

  gamesserver:
    build: ./game-server/
    expose:
      - "4000"
    ports:
      - "4000:4000"
