packages:
  - nextjs
  - game-server
  - tests
  - shared
allowBuilds:
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - bcrypt
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - "@prisma/engines"
  - esbuild
  - prisma
